//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMaitreDImporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinMaitreDImporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppGreen {
            get {
                object obj = ResourceManager.GetObject("AppGreen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppRed {
            get {
                object obj = ResourceManager.GetObject("AppRed", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ExternalOrder Ref=&quot;ORDER 001&quot;&gt;
        ///  &lt;Invoice&gt;101051&lt;/Invoice&gt;
        ///  &lt;Workstation&gt;3&lt;/Workstation&gt;
        ///  &lt;WaiterNumber&gt;5&lt;/WaiterNumber&gt;
        ///  &lt;DateOrdered&gt;2003-01-01&lt;/DateOrdered&gt;
        ///  &lt;TimeOrdered&gt;9:01:33&lt;/TimeOrdered&gt;
        ///  &lt;DateDelivery&gt;2003-01-05&lt;/DateDelivery&gt;
        ///  &lt;TimeDelivery&gt;20:30:00&lt;/TimeDelivery&gt;
        ///  &lt;TimePreparation&gt;20:00:00&lt;/TimePreparation&gt;
        ///  &lt;Function&gt;Delivery&lt;/Function&gt;
        ///  &lt;PickUp&gt;False&lt;/PickUp&gt;
        ///  &lt;SendToKitchen&gt;Yes&lt;/SendToKitchen&gt;
        ///  &lt;PrintPOS&gt;3&lt;/PrintPOS&gt;
        ///  &lt;Mode&gt;2&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
    }
}
